/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "welcome",
  "description": "描述",
  "base": "/docs/",
  "headTags": [
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress 介绍"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "小趴菜"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/hero.png"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/docs/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/docs/icons/apple-touch-icon-152x152.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/docs/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1f9e953a",
      "path": "/",
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000,
      "createdTime": 1681722402000
    },
    {
      "frontmatter": {},
      "regularPath": "/java/",
      "relativePath": "java/README.md",
      "key": "v-45ef6046",
      "path": "/java/",
      "headers": [
        {
          "level": 2,
          "title": "java readme",
          "slug": "java-readme"
        }
      ],
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000,
      "createdTime": 1681722402000
    },
    {
      "frontmatter": {},
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-463de97d",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "js readme",
          "slug": "js-readme"
        }
      ],
      "lastUpdated": "4/19/2023, 2:44:20 PM",
      "lastUpdatedTimestamp": 1681886660000,
      "createdTime": 1681722402000
    },
    {
      "title": "配置0",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-d71cad6e",
      "path": "/config.html",
      "headers": [
        {
          "level": 2,
          "title": "配置0",
          "slug": "配置0"
        },
        {
          "level": 2,
          "title": "配置1",
          "slug": "配置1"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3"
        },
        {
          "level": 2,
          "title": "配置2",
          "slug": "配置2"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-2"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-2"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-2"
        },
        {
          "level": 2,
          "title": "配置3",
          "slug": "配置3"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-3"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-3"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-3"
        },
        {
          "level": 2,
          "title": "配置44",
          "slug": "配置44"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-4"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-4"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-4"
        },
        {
          "level": 3,
          "title": "1-45",
          "slug": "_1-45"
        }
      ],
      "lastUpdated": "4/19/2023, 12:13:04 PM",
      "lastUpdatedTimestamp": 1681877584000,
      "createdTime": 1681722402000
    }
  ],
  "themeConfig": {
    "logo": "/hero.png",
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ]
  }
}