/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "welcome",
  "description": "描述",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/hero.png"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress 介绍"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "小趴菜"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1f9e953a",
      "path": "/",
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000
    },
    {
      "title": "配置0",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-d71cad6e",
      "path": "/config.html",
      "headers": [
        {
          "level": 2,
          "title": "配置0",
          "slug": "配置0"
        },
        {
          "level": 2,
          "title": "配置1",
          "slug": "配置1"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3"
        },
        {
          "level": 2,
          "title": "配置2",
          "slug": "配置2"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-2"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-2"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-2"
        },
        {
          "level": 2,
          "title": "配置3",
          "slug": "配置3"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-3"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-3"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-3"
        },
        {
          "level": 2,
          "title": "配置44",
          "slug": "配置44"
        },
        {
          "level": 3,
          "title": "1-1",
          "slug": "_1-1-4"
        },
        {
          "level": 3,
          "title": "1-2",
          "slug": "_1-2-4"
        },
        {
          "level": 3,
          "title": "1-3",
          "slug": "_1-3-4"
        },
        {
          "level": 3,
          "title": "1-45",
          "slug": "_1-45"
        }
      ],
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000
    },
    {
      "frontmatter": {},
      "regularPath": "/java/",
      "relativePath": "java/README.md",
      "key": "v-45ef6046",
      "path": "/java/",
      "headers": [
        {
          "level": 2,
          "title": "java readme",
          "slug": "java-readme"
        }
      ],
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000
    },
    {
      "frontmatter": {},
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-463de97d",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "js readme",
          "slug": "js-readme"
        }
      ],
      "lastUpdated": "4/17/2023, 5:06:42 PM",
      "lastUpdatedTimestamp": 1681722402000
    }
  ],
  "themeConfig": {
    "logo": "/hero.png",
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": "auto"
  }
}