name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        TARGET_REPO: wyf195075595/docs
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: https://www.xxx.com # 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